//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assets_Maintenance
    {
        public int AssetsMaintenanceID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public string PurchasedSpareParts { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public string ShopName { get; set; }
        public string Address { get; set; }
        public Nullable<int> ContactNumber { get; set; }
        public string Email { get; set; }
        public string OwnerName { get; set; }
        public Nullable<int> OwnerContact { get; set; }
        public byte[] Attachment { get; set; }
    }
}
